version: '3' # docker version
services:
  www:
    image: php:7.4-apache
    env_file:
      - .env
    volumes:
      - "./:/var/www/html" # sync project dir with container web dir
    ports:
      - 80:80
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
  db:
    image: mysql:latest
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306



#  docker-compose up --build